import os
def menu():
      while True:
           os.system("clear")
           os.system('                figlet Covid-19 | lolcat -d 1 -t -s 100')
           print('\033[1;36;40m<────────────────────────────────────>')
           print("")
           os.system('echo • To prevent the spread of COVID-19:')
           print("")
           os.system('echo • Clean your hands often. Use soap and water, or an alcohol-based hand rub. | lolcat -a -t')
           print("")
           os.system('echo • Maintain a safe distance from anyone who is coughing or sneezing.')
           print("")
           os.system('echo • Don’t touch your eyes, nose or mouth. | lolcat -a -t')
           print("")
           os.system('echo • Cover your nose and mouth with your bent elbow or a tissue when you cough or sneeze. | lolcat -a -t')
           print("")
           os.system('echo • Stay home if you feel unwell. | lolcat -a -t')
           print("")
           os.system('echo • If you have a fever, a cough, and difficulty breathing, seek medical attention. Call in advance. | lolcat -a -t')
           print("")
           os.system('echo • Follow the directions of your local health authority. | lolcat -a -t')
           print("")
           print('\033[1;92m • Press CTRL+D TO CLOSE')
           os.system('figlet | lolcat')
           break
menu()
